---
title: "UCPD Traffic Stops"
output: html_document
date: "2025-02-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1. Coding Environment Set-up

```{r load-packages,  results='asis'}

setwd("/Users/euijinkim/Downloads")
library(dplyr)
library(tidyverse)
library(gtools)

# END 
```

## 2. Data Cleaning and Exploratory Data Analysis

```{r data-clean1,  results='asis'}
# load beat location shapefile and traffic stops data
# combine traffic stops 2004-2022 data with 2023 data
beat_location_2012_2025 <- read.csv("PoliceBeatDec2012_20250122.csv")
raw_2004_2022 <- read.csv("UNIVERSITY OF CHICAGO POLICE.csv")
raw_2023 <- read.csv("2023_ucpd.csv")
setdiff(colnames(raw_2004_2022), colnames(raw_2023))
raw_combined = smartbind(raw_2004_2022, raw_2023) 
clean <- raw_combined[,c("id", "year", "record_ref", "AgencyCode", "agency_id", "DateOfStop", "TimeOfStop", "DurationOfStop", "ZIP", "VehicleMake", "VehicleYear", "DriversYearofBirth", "DriverSex", "ReasonForStop", "TypeOfMovingViolation", "BeatLocationOfStop", "driver_race", "search_conducted", "search_hit", "consent_search_requested", "consent_search_conducted", "dog_sniff", "dog_search_conducted", "dog_search_hit", "outcome")]

# summarize traffic stops by beat location variable
location_summary <- clean %>%
    group_by(year, BeatLocationOfStop) %>%
    summarise(count = n(), .groups = "drop") 

# clean beat location variable 
location_summary$beatlocations_clean <- gsub("\\\\", "", location_summary$BeatLocationOfStop)
location_summary$beatlocations_clean <- gsub("'", "", location_summary$beatlocations_clean)
location_summary$beatlocations_clean <- gsub("#", "", location_summary$beatlocations_clean)
location_summary$beatlocations_clean <- gsub("UC ", "", location_summary$beatlocations_clean)
location_summary$beatlocations_clean <- gsub("C ", "", location_summary$beatlocations_clean)
location_summary$beatlocations_clean <- gsub("UC", "", location_summary$beatlocations_clean)
location_summary$beatlocations_clean <- gsub("C", "", location_summary$beatlocations_clean)

location_recode <- c("N/A" = NA, "15:" = "15")

location_summary$beatlocations_clean <- 
  recode(location_summary$beatlocations_clean, !!!location_recode)

unique(location_summary$beatlocations_clean) 
# note: it seems that some beat locations are combined into one (eg - 222/132) but unclear why bc 222 and 132 are not contiguous. also unclear what VW means

# merge location summary (traffic stops) data with beat location shapefile
beat_location_2012_2025$beat_num_str <- as.character(beat_location_2012_2025$BEAT_NUM)
merged <- 
  left_join(location_summary, beat_location_2012_2025, 
            by=c('beatlocations_clean'= 'beat_num_str'))

# limit merge to post-2012 bc it seems like beat locations were updated in 2012
merged_2012_2025 <- merged[merged$year >= 2012,] 

# failed to merge on some beats - explore where they actually took place
na_beats <- merged[is.na(merged$BEAT_NUM), ]
na_beats_2012_2025 <- merged_2012_2025[is.na(merged_2012_2025$BEAT_NUM), ]
unique(na_beats_2012_2025$beatlocations_clean)

# beat locations that seem too far from HP - explore where they actually took place
weird_140 <- raw_2022[raw_2022$BeatLocationOfStop == "140",] 
weird_131 <- raw_2022[raw_2022$BeatLocationOfStop == "131",] 

# END 
```




